In [1]:
import pandas as pd
import numpy as np
import pickle
from sklearn.linear_model import LinearRegression

In [2]:
with open('../../Downloads/distributions/merged_est.pkl','rb') as f:
    merged = pickle.load(f)

In [3]:
def adjust_to_thirty_minute(steps):
    return steps.fillna(0).tz_localize(None).resample('30T').sum().fillna(0)

In [12]:
with open('../../Downloads/distributions/dists_intervention_anti_sed_3_8.pkl','rb') as f:
    dists_sed = pickle.load(f)
with open('../../Downloads/distributions/key_matches_intervention_anti_sed_3_8.pkl','rb') as f:
    matches_sed = pickle.load(f)
with open('../../Downloads/distributions/dists_actsugg_3_8.pkl','rb') as f:
    dists_act = pickle.load(f)
with open('../../Downloads/distributions/key_matches_act_sugg_3_8.pkl','rb') as f:
    matches_act = pickle.load(f)

In [3]:
def get_activity_suggestion(user_df):
    to_return = {}
    for index,row in user_df.iterrows():
        if type(row['avail'])==bool and row['avail']:
            if type(row['send.active'])==bool:
                sent = row['send.active']
                i = index.round('30T').tz_localize(None)
                to_return[i]=sent
    return to_return

In [4]:
def get_anti_sedentary(user_df):
    to_return = {}
    for index,row in user_df.iterrows():
        if type(row['avail'])==bool and row['avail']:
            if type(row['send.sedentary'])==bool:
                sent = row['send.sedentary']
                i = index.round('30T').tz_localize(None)
                to_return[i]=sent
    return to_return

In [5]:
all_antis = {k:get_anti_sedentary(v) for k,v in merged.items() if k!=4}
all_actives = {k:get_activity_suggestion(v) for k,v in merged.items() if k!=4}


In [6]:
def get_all_dow():
    to_return = {0:{'True':[],'False':[]},1:{'True':[],'False':[]}}
    for k,v in merged.items():
        if k!=4:
            
            a = all_actives[k]
            b = all_antis[k]
        #print(len(a))
            xs = []
            ys = []
            if k!=4:
                steps = adjust_to_thirty_minute(v['steps'])
                for i,s in steps.iteritems():
                    dow = i.dayofweek
                    if i in a and i in b and i.hour>=9 and i.hour<21:
                    #print('found')
                        action = a[i]
                    #print(action)
                    #int(dow==5 or dow==6)
                        if action:
                            to_return[int(dow==5 or dow==6)]['True'].append(s)
                        elif b[i]
                      
                                to_return[int(dow==5 or dow==6)]['False'].append(s)
                        #elif b[i]:
                        #else:
                            #to_return[int(dow==5 or dow==6)]['False'].append(s)
                    #if i in b and i.hour>=9 and i.hour<21:
                       
                        #action = b[i]
                    #print(action)
                    #int(dow==5 or dow==6)
                        #if action:
                            #to_return[int(dow==5 or dow==6)]['False'].append(s)
    return to_return

SyntaxError: invalid syntax (<ipython-input-6-8658762c36af>, line 22)

In [28]:
def get_all_tod():
    to_return = {0:{'True':[],'False':[]},1:{'True':[],'False':[]}}
    for k,v in merged.items():
        if k!=4:
            
            a = all_actives[k]
            b = all_antis[k]
        #print(len(a))
            xs = []
            ys = []
            if k!=4:
                steps = adjust_to_thirty_minute(v['steps'])
                for i,s in steps.iteritems():
                    hour = hour_ids[i.hour]
                    if i in a and i in b and hour!=2:
                    #print('found')
                        action = a[i]
                    #print(action)
                    #int(dow==5 or dow==6)
                        if action:
                            to_return[int(hour)]['True'].append(s)
                        elif b[i]
                
                                to_return[int(hour)]['False'].append(s)
                        #elif b[i]:
                        #else:
                            #to_return[int(hour)]['False'].append(s)
                    #if i in b and i.hour>=9 and i.hour<21:
                       
                        #action = b[i]
                    #print(action)
                    #int(dow==5 or dow==6)
                        #if action:
                            #to_return[int(dow==5 or dow==6)]['False'].append(s)
    return to_return

SyntaxError: invalid syntax (<ipython-input-28-155330e3c2db>, line 22)

In [7]:
def get_all_temperature():
    to_return = {0:{'True':[],'False':[]},1:{'True':[],'False':[]}}
    for k,v in merged.items():
        if k!=4:
            
            a = all_actives[k]
            b = all_antis[k]
        #print(len(a))
            xs = []
            ys = []
            if k!=4:
                steps = adjust_to_thirty_minute(v['steps'])
                for i,s in steps.iteritems():
                    temp = None
                    if i in temps[k]:
                        temp = temps[k][i]
                    if i in a and i in b and i.hour>=9 and i.hour<21:
                    #print('found')
                        action = a[i]
                    #print(action)
                    #int(dow==5 or dow==6)
                        if  temp is not None:
                            #to_return[int(temp)]['True'].append(s)
                        
                            if action:
                                to_return[int(temp)]['True'].append(s)
                            elif b[i]:
                         
                                    to_return[int(temp)]['False'].append(s)
                    #if i in b and i.hour>=9 and i.hour<21:
                       
                        #action = b[i]
                    #print(action)
                    #int(dow==5 or dow==6)
                        #if action:
                            #to_return[int(dow==5 or dow==6)]['False'].append(s)
    return to_return

In [8]:
def get_all_last_steps():
    to_return = {0:{'True':[],'False':[]},1:{'True':[],'False':[]}}
    for k,v in merged.items():
        if k!=4:
            
            a = all_actives[k]
            b = all_antis[k]
        #print(len(a))
            xs = []
            ys = []
            if k!=4:
                steps = adjust_to_thirty_minute(v['steps'])
                for i,s in steps.iteritems():
                    temp = None
                    if i in last_steps[k]:
                        temp = last_steps[k][i]
                    if i in a and i in b and i.hour>=9 and i.hour<21:
                    #print('found')
                        action = a[i]
                    #print(action)
                    #int(dow==5 or dow==6)
                    #int(dow==5 or dow==6)
                        if  temp is not None:
                            #to_return[int(temp)]['True'].append(s)
                        
                            if action:
                                to_return[int(temp)]['True'].append(s)
                            elif b[i]:
                    
                                    to_return[int(temp)]['False'].append(s)
                    #if i in b and i.hour>=9 and i.hour<21:
                       
                        #action = b[i]
                    #print(action)
                    #int(dow==5 or dow==6)
                        #if action:
                            #to_return[int(dow==5 or dow==6)]['False'].append(s)
    return to_return

In [9]:
def get_all_location():
    to_return = {0:{'True':[],'False':[]},1:{'True':[],'False':[]}}
    for k,v in merged.items():
        if k!=4:
            
            a = all_actives[k]
            b = all_antis[k]
        #print(len(a))
            xs = []
            ys = []
            if k!=4:
                steps = adjust_to_thirty_minute(v['steps'])
                for i,s in steps.iteritems():
                    temp = None
                    if i in location[k]:
                        temp = location[k][i]
                    if i in a and i in b and i.hour>=9 and i.hour<21:
                    #print('found')
                        action = a[i]
                    #print(action)
                    #int(dow==5 or dow==6)
                        if  temp is not None:
                            #to_return[int(temp)]['True'].append(s)
                        
                            if action:
                                to_return[int(temp)]['True'].append(s)
                            elif b[i]:
                      
                                    to_return[int(temp)]['False'].append(s)
                            
                        #elif b[i] and temp is not None:
                        #else:
                            #to_return[int(temp)]['False'].append(s)
                    #if i in b and i.hour>=9 and i.hour<21:
                       
                        #action = b[i]
                    #print(action)
                    #int(dow==5 or dow==6)
                        #if action:
                            #to_return[int(dow==5 or dow==6)]['False'].append(s)
    return to_return

In [10]:
def get_intercept():
    to_return = {'True':[],'False':[]}
    for k,v in merged.items():
        if k!=4:
            
            a = all_actives[k]
            b = all_antis[k]
        #print(len(a))
            xs = []
            ys = []
            if k!=4:
                steps = adjust_to_thirty_minute(v['steps'])
                for i,s in steps.iteritems():
                    dow = i.dayofweek
                    if i in a and i in b and i.hour>=9 and i.hour<21:
                    #print('found')
                        action = a[i]
                    #print(action)
                    #int(dow==5 or dow==6)
                        if action:
                            to_return['True'].append(s)
                        #else:
                            #to_return['False'].append(s)
                        #elif b[i]:
                        elif b[i]:
                    
                                to_return['False'].append(s)
                    #if i in b and i.hour>=9 and i.hour<21:
                       
                        #action = b[i]
                    #print(action)
                    #int(dow==5 or dow==6)
                        #if action:
                            #to_return[int(dow==5 or dow==6)]['False'].append(s)
    return to_return

In [ ]:
test = get_all_tod()

In [ ]:
tn = get_intercept()

In [15]:
import math
def make_x_y(d):
    X = []
    y = []
    
    mean_zero = np.array([math.log(s+.5) for s in d[0]['True']]).mean()-np.array([math.log(s+.5) for s in d[0]['False']]).mean()
    mean_one = np.array([math.log(s+.5) for s in d[1]['True']]).mean()-np.array([math.log(s+.5) for s in d[1]['False']]).mean()
    X = [[0],[1]]
    y = [mean_zero,mean_one]
    return X,y

In [16]:
import math
def make_x_y_intercept(d):
    X = []
    y = []
    print( len(d['True']))
    print( len(d['False']))
    
    mean_zero = np.array([math.log(s+.5) for s in d['True']]).mean()-np.array([math.log(s+.5) for s in d['False']]).mean()
    X = [[0]]
    y = [mean_zero]
    return X,y

In [17]:
import math
def make_x_y_fancy(d):
    X = []
    y = []
    
    
    mzero_one,szero_one = get_mean_std( d[0]['True'])
    mzero_zero,szero_zero = get_mean_std( d[0]['False'])
    
    mone_one,sone_one = get_mean_std( d[1]['True'])
    mone_zero,sone_zero = get_mean_std( d[1]['False'])
    
    mean_zero = mzero_one-mzero_zero
    mean_one = mone_one-mone_zero
    
    
    X = [[0],[1]]
    y = [mean_zero,mean_one]
    return X,y

In [18]:
def get_mean_std(raw_array):
    arr = [s+.5 for s in raw_array]
    
    phi = np.sqrt(np.array(arr).std()**2+np.array(arr).mean()**2)
    
    normal_mean = math.log(np.array(arr).mean()**2/phi)
    normal_std = np.sqrt(math.log(phi**2/np.array(arr).mean()**2))
    return normal_mean,normal_std

In [19]:
import math
def make_x_y_intercept(d):
    X = []
    y = []
    o = min( len(d['True']),len(d['False']))

    
    #mean_zero = np.array([math.log(s+.5) for s in d['True']]).mean()-np.array([math.log(s+.5) for s in d['False']]).mean()
    m_one,std_one = get_mean_std( d['True'])
    
    m_zero,std_zero = get_mean_std( d['False'])
    
    for i in range(o):
        X.append([0])
        y_one = np.random.normal(loc =m_one,scale=std_one)
        y_two = np.random.normal(loc =m_zero,scale=std_zero)
        y.append(y_one-y_two)
    return X,y

In [47]:
test = get_all_temperature()

In [48]:
X,y = make_x_y_fancy(test)
reg = LinearRegression().fit(X, y)
reg.coef_

array([0.18145672])

[-0.01597239389423022, 0.38353261266077876]

In [297]:
reg = LinearRegression().fit(X, y)

In [298]:
reg.coef_

array([0.39950501])

In [248]:
reg.intercept_

0.22518209432175196

In [315]:
X,y = make_x_y_intercept(tn)
reg = LinearRegression().fit(X, y)
reg.coef_
reg.intercept_

0.24084978362502385

In [257]:
y

[0.20298266707683954]

In [90]:
np.array(test[1]['True']).mean()

220.20762711864407

In [89]:
np.array(test[1]['False']).shape

(1021,)

In [91]:
y

[19.762575975894237, 0.21252427829148246]

In [20]:
with open('../../Downloads/distributions/hour_to_id.pkl','rb') as f:
    hour_ids = pickle.load(f)
with open('../../Downloads/distributions/tonly_lookup_dict.pkl','rb') as f:
    temps = pickle.load(f)
with open('../../Downloads/distributions/newlog_steps_last30min.pkl','rb') as f:
    last_steps = pickle.load(f)
with open('../../Downloads/distributions/location_lookup_dict_basics.pkl','rb') as f:
    location = pickle.load(f)


In [103]:
ys = []
xs=[]
sigs = []
for k,v in dists_sed.items():
    if 'aint-1' in k and len(k.split('-'))==14 and k in dists_act and 'tod-2' not in k:
        occurs= min(v[2],dists_act[k][2])
        sigs.append(v[1])
        sigs.append(dists_act[k][1])
        
        for j in range(occurs):
        #if  v[2]>35 and  dists_act[k][2]>35:
            
            y = dists_act[k][0]-v[0]
            #np.random.normal(dists_act[k][0],dists_act[k][1])-np.random.normal(v[0],v[1])
            p = k.split('-')
            x = [1]+[int(p[i]) for i in range(5,len(p),2)]
            ys.append(y)
            xs.append(x)
print(len(xs))
reg = LinearRegression().fit(xs, ys)
print(np.array([reg.intercept_]+reg.coef_))
print(reg.intercept_)
print(len(xs))

1379
[ 0.04772972  0.0696645   0.21549613  0.24941052 -0.22475609  0.22540878]
0.04772972147336857
1379


In [106]:
np.percentile(sigs,25)

0.829691667107783

In [100]:
ys = []
xs=[]
for k,v in dists_act.items():
    
    if 'aint-1' in k and len(k.split('-'))==14 and 'aint-0-'+k[7:] in dists_act and 'tod-2' not in k :
        #print('aint-0-'+k[7:] )
        #print(v[2])
        occurs= min(v[2],dists_act['aint-0-'+k[7:]][2])
        for j in range(occurs):
        #if  v[2]>35 and  dists_act['aint-0-'+k[7:]][2]>35:
            #y = np.random.normal(v[0],v[1])-np.random.normal(dists_act['aint-0-'+k[7:]][0],dists_act['aint-0-'+k[7:]][1])
            y=v[0]-dists_act['aint-0-'+k[7:]][0]
            p = k.split('-')
            x = [1]+[int(p[i]) for i in range(5,len(p),2)]
            ys.append(y)
            xs.append(x)
print(len(xs))
reg = LinearRegression().fit(xs, ys)
print(reg.coef_)
print(reg.intercept_)
print(len(xs))

1716
[ 0.         -0.0632193  -0.04564373  0.02496729 -0.19398716  0.24379593]
0.19472243999853708
1716


In [53]:
len(xs)

34

In [52]:
reg = LinearRegression().fit(xs, ys)
print(reg.coef_)
print(reg.intercept_)

[ 0.         -0.01125987  0.0965933   0.2353184  -0.24098841  0.36741346]
0.020884223339177332


In [25]:
ys

[-3.0156288879987927,
 1.0452144083594543,
 0.7379065144300281,
 -0.6090635823879742,
 0.2508776665151009,
 0.31623322573268187,
 1.696856837520671,
 3.193613157354273,
 2.7739222696650465,
 5.131982005737408,
 6.014456327740522,
 0.0,
 -5.017661558073788,
 0.2388282485008082,
 1.0301685896936918,
 -3.2298212296958426,
 -1.0294229143566214,
 1.3020916706173464,
 2.394808946866181,
 -0.0640413120112786,
 0.1701445978879912,
 0.025086462433566048,
 -1.5485703205086843,
 0.7811547311410032,
 -0.46518846001800007,
 2.072405714218731,
 0.12233529633757279,
 1.9374753945044745,
 4.078290966836959,
 -0.9942849082828271,
 3.8066624897703196,
 0.2374507340714631,
 -0.3847584611212369,
 0.5325334001333522,
 -0.10635223706021968,
 0.2947017009192603,
 -0.3424801065206049,
 -0.08439480306135039,
 0.15207494742079408,
 0.5942858290564486,
 0.8779162088666332,
 0.46159610831208564,
 -0.2848422664753345,
 -0.08998475896447466,
 -0.09280191112020653,
 1.316205324967135,
 -0.18676606203885804,
 0.22229