In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression
import pickle

In [4]:
with open('../../Downloads/distributions/dists_anti_sedentary_3_25.pkl','rb') as f:
    dists_sed = pickle.load(f)
with open('../../Downloads/distributions/key_matches_anti_sedentary_3_25.pkl','rb') as f:
    matches_sed = pickle.load(f)
with open('../../Downloads/distributions/dists_activity_suggestion_3_25.pkl','rb') as f:
    dists_act = pickle.load(f)
with open('../../Downloads/distributions/key_matches_activity_suggestion_3_25.pkl','rb') as f:
    matches_act = pickle.load(f)

In [6]:
def get_all_states():
    gids = [1,2]
    tod = [0,1]
    dow  = [0,1]
    pretreatment = [0,1]
    temp = [0,1]
    loc = [0,1]
    
    all_states = []
    st = ['gid','tod','dow','pre','loc']
    
    for g in gids:
        for t in tod:
            for d in dow:
                #for tp in temp:
                    for p in pretreatment:
                        for l in loc:
                            all_states.append([g,t,d,p,l])
    all_keys = []
    for s in all_states:
        new_key = ['aint','1']
        for i in range(len(s)):
            new_key.append(st[i])
            new_key.append(str(s[i]))
        all_keys.append('-'.join(new_key))
    return all_keys

In [7]:
def get_all_states_both():
    gids = [1,2]
    tod = [0,1]
    dow  = [0,1]
    pretreatment = [0,1]
    temp = [0,1]
    loc = [0,1]
    actions = [0,1]
    all_states = []
    st = ['gid','tod','dow','pre','loc']
    for act in actions:
        for g in gids:
            for t in tod:
                for d in dow:
                    #for tp in temp:
                        for p in pretreatment:
                            for l in loc:
                                all_states.append([g,t,d,p,l])
    all_keys = []
    for s in all_states:
        new_key = []
        #new_key = ['aint','1']
        for i in range(len(s)):
            new_key.append(st[i])
            new_key.append(str(s[i]))
        all_keys.append('-'.join(new_key))
    return all_keys

In [111]:
def get_all_states_short():
    gids = [1,2]
    tod = [0,1]
    dow  = [0,1]
    pretreatment = [0,1]
    temp = [0,1]
    loc = [0,1]
    actions = [0,1]
    all_states = []
    st = ['tod','dow','wea','pre','loc']
    for act in actions:
        for g in gids:
            for t in tod:
                for d in dow:
                    for tp in temp:
                        for p in pretreatment:
                            for l in loc:
                                all_states.append([t,d,tp,p,l])
    all_keys = []
    for s in all_states:
        new_key = []
        #new_key = ['aint','1']
        for i in range(len(s)):
            new_key.append(st[i])
            new_key.append(str(s[i]))
        all_keys.append('-'.join(new_key))
    return all_keys

In [8]:
s = get_all_states()

In [9]:
sb = get_all_states_both()

In [28]:
shorties = get_all_states_short()

In [112]:
shortiesl = get_all_states_short()

In [10]:
def get_x_y(state_key):
    root = matches_sed[ state_key]
    mean_control = dists_sed[root][0]
    other = matches_act[state_key]
    mean_treatment = dists_act[other][0]
    y = mean_treatment - mean_control 
    parts = state_key.split('-')
    x = [1]
    occurs = min( dists_sed[root][2],dists_act[other][2])

    if True:
    #len(root.split('-'))==14 and len(other.split('-'))==14:
        #print(root)
        #print(other)
        print(state_key)
        for i in range(5,len(parts),2):

                x.append(int(parts[i]))
        print(x)
    return x,y,dists_sed[root][1],dists_act[other][1],occurs,root,other
    

In [11]:
def get_x_y_check(state_key):
    #root = matches_sed[state_key]
    #mean_control = dists_sed[root][0]
    
    treatment = 'aint-1-'+state_key
    control = 'aint-0-'+state_key
    
    tother = matches_act[treatment]
    mean_treatment = dists_act[tother][0]
    
    cother = matches_act[control]
    mean_control = dists_act[cother][0]
    
    y = mean_treatment - mean_control 
    parts = state_key.split('-')
    #x = [1]
    x=[]
    #occurs = min( dists_sed[root][2],dists_act[other][2])
    #y = mean_treatment
    
    for i in range(5,len(parts),2):
        #if parts[1]=='2':
            #print(parts[i])
            #print(parts[i-1])
            x.append(int(parts[i]))
    return x,y
#,occurs

In [12]:
def get_x_y_dow(state_key):
    #root = matches_sed[state_key]
    #mean_control = dists_sed[root][0]
    
    treatment = 'aint-1-'+state_key
    control = 'aint-0-'+state_key
    
    tother = matches_act[treatment]
    mean_treatment = dists_act[tother][0]
    
    cother = matches_act[control]
    mean_control = dists_act[cother][0]
    
    y = mean_treatment - mean_control 
    parts = state_key.split('-')
    #x = [1]
    x=[int(parts[5])]
    #occurs = min( dists_sed[root][2],dists_act[other][2])
    #y = mean_treatment
    
   
    return x,y
#,occurs

In [219]:
def get_all_xs_all_ys():
    all_xs = []
    all_ys = []
    found = []
    sigmas = []
    seenone = set([])
    seentwo = set([])
    for sk in s:
        x,y,zone,ztwo,o,rootone,roottwo =  get_x_y(sk)
        if rootone not in seenone and roottwo not in seentwo:
            #for j in range(o):
        #if 'gid-2' in sk:
        #if len(x)>1:
                all_xs.append(x)
                all_ys.append(y)
                found.append(sk)
                sigmas.append(zone)
                sigmas.append(ztwo)
        seenone.add(rootone)
        seentwo.add(roottwo)
    return all_xs,all_ys,found,sigmas

In [210]:
y

[0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.20407455457750245,
 0.2040745

In [220]:
X,y,f,sigs = get_all_xs_all_ys()

aint-1-gid-1-tod-0-dow-0-wea-0-pre-0-loc-0
[1, 0, 0, 0, 0, 0]
aint-1-gid-1-tod-0-dow-0-wea-0-pre-0-loc-1
[1, 0, 0, 0, 0, 1]
aint-1-gid-1-tod-0-dow-0-wea-0-pre-1-loc-0
[1, 0, 0, 0, 1, 0]
aint-1-gid-1-tod-0-dow-0-wea-0-pre-1-loc-1
[1, 0, 0, 0, 1, 1]
aint-1-gid-1-tod-0-dow-0-wea-1-pre-0-loc-0
[1, 0, 0, 1, 0, 0]
aint-1-gid-1-tod-0-dow-0-wea-1-pre-0-loc-1
[1, 0, 0, 1, 0, 1]
aint-1-gid-1-tod-0-dow-0-wea-1-pre-1-loc-0
[1, 0, 0, 1, 1, 0]
aint-1-gid-1-tod-0-dow-0-wea-1-pre-1-loc-1
[1, 0, 0, 1, 1, 1]
aint-1-gid-1-tod-0-dow-1-wea-0-pre-0-loc-0
[1, 0, 1, 0, 0, 0]
aint-1-gid-1-tod-0-dow-1-wea-0-pre-0-loc-1
[1, 0, 1, 0, 0, 1]
aint-1-gid-1-tod-0-dow-1-wea-0-pre-1-loc-0
[1, 0, 1, 0, 1, 0]
aint-1-gid-1-tod-0-dow-1-wea-0-pre-1-loc-1
[1, 0, 1, 0, 1, 1]
aint-1-gid-1-tod-0-dow-1-wea-1-pre-0-loc-0
[1, 0, 1, 1, 0, 0]
aint-1-gid-1-tod-0-dow-1-wea-1-pre-0-loc-1
[1, 0, 1, 1, 0, 1]
aint-1-gid-1-tod-0-dow-1-wea-1-pre-1-loc-0
[1, 0, 1, 1, 1, 0]
aint-1-gid-1-tod-0-dow-1-wea-1-pre-1-loc-1
[1, 0, 1, 1, 1, 1]
aint-1-g

In [199]:
nfs = [i[13:] for i in f]

In [92]:
def aggregate_one(dists,matches):
    
    to_return = {}
    
    for k,v in matches.items():
        
        if len(v.split('-'))==12 and 'aint-1' in v and 'tod-2' not in v:
            new_key = v[13:]
            #print(v)
            #print(k)
            #print(new_key)
            #print(dists[v])
            #if new_key not in to_return:
            to_return[new_key]=dists[v]
            #else:
                #to_return[new_key].append(dists[v])
    return to_return
    

In [67]:
ai = aggregate_one(dists_sed,matches_sed)

In [184]:
def get_entries_base(needs):
    antised = aggregate_one(dists_sed,matches_sed)
    actsugg = aggregate_one(dists_act,matches_act)
    
    X = []
    y = []
    sigmas = []
    for n in needs:
        for loc in [0,1]:
            y_one = actsugg[n]
            y_zero = antised[n]
            
            parts = [int(n.split('-')[i]) for i in range(1,len(n.split('-')),2)]
            parts.append(loc)
            parts = [1]+parts
            #print(parts)
            X.append(parts)
            y.append(y_one[0]-y_zero[0])
            sigmas.append(actsugg[n][1])
            sigmas.append(antised[n][1])
    return X,y,sigmas
    

In [123]:
#add these things back in and see what happens
needs = []
for sh in set(shortiesl):
    if sh not in nfs:
        needs.append(sh)

In [143]:
def get_special_needs(needs):
    goods = set([])
    for n in needs:
        stem = n[:23]

        if stem+'-loc-0' in needs and stem+'-loc-1' in needs:
            goods.add(stem)
    return goods

In [144]:
sn = get_special_needs(set(needs))

In [145]:
sn

{'tod-0-dow-1-wea-0-pre-0',
 'tod-0-dow-1-wea-0-pre-1',
 'tod-0-dow-1-wea-1-pre-1',
 'tod-1-dow-1-wea-0-pre-1',
 'tod-1-dow-1-wea-1-pre-0',
 'tod-1-dow-1-wea-1-pre-1'}

In [159]:
Xbase,ybase,sigs_two = get_entries_base(sn)

In [149]:
newX = X+Xbase
newy = y+ybase

In [221]:
reg = LinearRegression().fit(X, y)

In [222]:
reg.coef_

array([ 0.        , -0.128424  ,  0.12114183,  0.17851326, -0.20642121,
        0.00823339])

In [223]:
 reg.intercept_

0.14791128192413638

In [171]:
np.percentile(np.array(sigs),75)

1.2613365628881554

In [224]:
len(X)

42

In [52]:
reg.coef_

array([ 0.        , -0.06405887,  0.09447067,  0.16481901, -0.20736237,
        0.01136896])

In [53]:
 reg.intercept_

0.1318755103596786

In [23]:
with open('../../Downloads/distributions/day_to_id.pkl','rb') as f:
    h = pickle.load(f)

In [226]:
X

[[1, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 1, 0],
 [1, 0, 0, 1, 0, 0],
 [1, 0, 0, 1, 1, 0],
 [1, 0, 1, 0, 0, 0],
 [1, 0, 1, 0, 1, 0],
 [1, 0, 1, 1, 0, 0],
 [1, 0, 1, 1, 1, 0],
 [1, 1, 0, 0, 0, 0],
 [1, 1, 0, 0, 1, 0],
 [1, 1, 0, 1, 0, 0],
 [1, 1, 0, 1, 1, 0],
 [1, 1, 1, 0, 0, 0],
 [1, 1, 1, 0, 1, 0],
 [1, 1, 1, 1, 0, 0],
 [1, 1, 1, 1, 1, 0],
 [1, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 1, 0],
 [1, 0, 0, 0, 1, 1],
 [1, 0, 0, 1, 0, 0],
 [1, 0, 0, 1, 0, 1],
 [1, 0, 0, 1, 1, 0],
 [1, 0, 0, 1, 1, 1],
 [1, 0, 1, 0, 0, 0],
 [1, 0, 1, 0, 1, 0],
 [1, 0, 1, 1, 0, 0],
 [1, 0, 1, 1, 0, 1],
 [1, 0, 1, 1, 1, 0],
 [1, 1, 0, 0, 0, 0],
 [1, 1, 0, 0, 0, 1],
 [1, 1, 0, 0, 1, 0],
 [1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0],
 [1, 1, 0, 1, 0, 1],
 [1, 1, 0, 1, 1, 0],
 [1, 1, 0, 1, 1, 1],
 [1, 1, 1, 0, 0, 0],
 [1, 1, 1, 0, 0, 1],
 [1, 1, 1, 0, 1, 0],
 [1, 1, 1, 1, 0, 0],
 [1, 1, 1, 1, 1, 0]]

In [24]:
h

{0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 1, 6: 1}

In [67]:
def get_all_xs_all_ys_dow():
    ymean =[]
    ymean_wk = []
    for sk in sb:
        x,y =  get_x_y_dow(sk)
        if 'dow-0' in sk:
            
            ymean.append(y)
        elif 'dow-1' in sk:
            ymean_wk.append(y)
        

    return [[0],[1]],[np.array(ymean).mean(),np.array(ymean_wk).mean()]

In [68]:
X,y = get_all_xs_all_ys_dow()

In [69]:
reg = LinearRegression().fit(X, y)
reg.coef_

array([0.03572201])

In [70]:
    treatment = 'aint-1-'+state_key
    control = 'aint-0-'+state_key
    
    tother = matches_act[treatment]
    mean_treatment = dists_act[tother][0]
    
    cother = matches_act[control]
    mean_control = dists_act[cother][0

[0.16766899117124023, 0.20339099940289906]

In [134]:
def get_all_xs_all_ys_dow_fancy():
    y_0_1 = []
    y_0_0 = []
    y_1_1 = []
    y_1_0 = []
    
    seen = set([])
    
    for k,v in matches_act.items():
        if 'dow-0' in k and 'aint-1' in k:
            if len(v.split('-'))==10:
                
                y_0_1.append( dists_act[v][0])
            seen.add(v)
        elif 'dow-0'in k and 'aint-0' in k:
            if len(v.split('-'))==10:
                y_0_0.append( dists_act[v][0])
            seen.add(v)
        elif 'dow-1' in k and 'aint-0' in k:
            if len(v.split('-'))==10:
                y_1_0.append( dists_act[v][0])
            seen.add(v)
            #print('found')
        elif 'dow-1' in k and 'aint-1' in k:
            #print('found')
            if len(v.split('-'))==10:
                y_1_1.append( dists_act[v][0])
            seen.add(v)
    return np.array(y_0_1),np.array(y_0_0),np.array(y_1_0),np.array(y_1_1)

In [135]:
looks = get_all_xs_all_ys_dow_fancy()

In [136]:
looks[0].mean()

4.010646512693568

In [137]:
looks[1].mean()

4.294580149234434

In [138]:
looks[3].mean()

3.8597302105200364

In [139]:
looks[2].mean()

3.718651969105231

In [17]:
[v for k,v in matches_act.items() if 'gid-1' in k]

['aint-0-tod-2-dow-1-wea-0-pre-0',
 'aint-0-gid-1-tod-2-dow-0-wea-0-pre-0',
 'aint-0-tod-1-dow-0-wea-0-pre-1',
 'aint-0-dow-1-wea-0-pre-1',
 'aint-0-tod-2-dow-1-wea-1-pre-0',
 'aint-0-tod-2-dow-0-wea-1-pre-0',
 'aint-1-tod-0-dow-0-wea-0-pre-0',
 'aint-0-gid-1-dow-0-wea-0-pre-1',
 'aint-1-tod-0-dow-0-wea-0-pre-1',
 'aint-1-tod-0-dow-1-wea-0-pre-1',
 'aint-1-dow-1-wea-0-pre-1',
 'aint-0-gid-1-dow-0-wea-0-pre-1',
 'aint-0-gid-1-dow-0-wea-1-pre-1',
 'aint-0-gid-1-tod-1-dow-0-wea-1-pre-0',
 'aint-0-gid-1-tod-1-dow-0-wea-1-pre-1',
 'aint-0-tod-0-dow-1-wea-1-pre-0',
 'aint-1-tod-0-dow-1-wea-1-pre-1',
 'aint-1-tod-1-dow-0-wea-1-pre-1',
 'aint-1-dow-0-wea-0-pre-1',
 'aint-0-tod-0-dow-0-wea-0-pre-1',
 'aint-1-tod-1-dow-0-wea-0-pre-0',
 'aint-1-tod-2-dow-1-wea-0-pre-0',
 'aint-1-tod-0-dow-1-wea-0-pre-0',
 'aint-1-tod-1-dow-1-wea-1-pre-1',
 'aint-1-tod-1-dow-1-wea-0-pre-0',
 'aint-1-tod-1-dow-0-wea-0-pre-1',
 'aint-1-tod-1-dow-1-wea-1-pre-0',
 'aint-0-tod-0-dow-0-wea-0-pre-1',
 'aint-0-tod-0-dow-1

In [193]:
6**.5

2.449489742783178