In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
import pickle

In [8]:
with open('../../Downloads/distributions/dists_intervention_anti_sed_3_8.pkl','rb') as f:
    dists_sed = pickle.load(f)
with open('../../Downloads/distributions/key_matches_intervention_anti_sed_3_8.pkl','rb') as f:
    matches_sed = pickle.load(f)
with open('../../Downloads/distributions/dists_actsugg_3_8.pkl','rb') as f:
    dists_act = pickle.load(f)
with open('../../Downloads/distributions/key_matches_act_sugg_3_8.pkl','rb') as f:
    matches_act = pickle.load(f)

In [9]:
def get_all_states():
    gids = [1,2]
    tod = [0,1]
    dow  = [0,1]
    pretreatment = [0,1]
    temp = [0,1]
    loc = [0,1]
    
    all_states = []
    st = ['gid','tod','dow','wea','pre','loc']
    
    for g in gids:
        for t in tod:
            for d in dow:
                for tp in temp:
                    for p in pretreatment:
                        for l in loc:
                            all_states.append([g,t,d,tp,p,l])
    all_keys = []
    for s in all_states:
        new_key = ['aint','1']
        for i in range(len(s)):
            new_key.append(st[i])
            new_key.append(str(s[i]))
        all_keys.append('-'.join(new_key))
    return all_keys

In [10]:
def get_all_states_both():
    gids = [1,2]
    tod = [0,1]
    dow  = [0,1]
    pretreatment = [0,1]
    temp = [0,1]
    loc = [0,1]
    actions = [0,1]
    all_states = []
    st = ['gid','tod','dow','wea','pre','loc']
    for act in actions:
        for g in gids:
            for t in tod:
                for d in dow:
                    for tp in temp:
                        for p in pretreatment:
                            for l in loc:
                                all_states.append([g,t,d,tp,p,l])
    all_keys = []
    for s in all_states:
        new_key = []
        #new_key = ['aint','1']
        for i in range(len(s)):
            new_key.append(st[i])
            new_key.append(str(s[i]))
        all_keys.append('-'.join(new_key))
    return all_keys

In [11]:
s = get_all_states()

In [12]:
sb = get_all_states_both()

In [38]:
def get_x_y(state_key):
    root = matches_sed[ 'aint-1-'+state_key]
    mean_control = dists_sed[root][0]
    other = matches_act['aint-1-'+state_key]
    mean_treatment = dists_act[other][0]
    y = mean_treatment - mean_control 
    parts = state_key.split('-')
    x = [1]
    occurs = min( dists_sed[root][2],dists_act[other][2])

    
    for i in range(3,len(parts),2):

            x.append(int(parts[i]))
    return x,y
    

In [30]:
def get_x_y_check(state_key):
    #root = matches_sed[state_key]
    #mean_control = dists_sed[root][0]
    
    treatment = 'aint-1-'+state_key
    control = 'aint-0-'+state_key
    
    tother = matches_act[treatment]
    mean_treatment = dists_act[tother][0]
    
    cother = matches_act[control]
    mean_control = dists_act[cother][0]
    
    y = mean_treatment - mean_control 
    parts = state_key.split('-')
    #x = [1]
    x=[]
    #occurs = min( dists_sed[root][2],dists_act[other][2])
    #y = mean_treatment
    
    for i in range(3,len(parts),2):
        #if parts[1]=='2':
            #print(parts[i])
            #print(parts[i-1])
            x.append(int(parts[i]))
    return x,y
#,occurs

In [43]:
def get_x_y_dow(state_key):
    #root = matches_sed[state_key]
    #mean_control = dists_sed[root][0]
    
    treatment = 'aint-1-'+state_key
    control = 'aint-0-'+state_key
    
    tother = matches_act[treatment]
    mean_treatment = dists_act[tother][0]
    
    cother = matches_act[control]
    mean_control = dists_act[cother][0]
    
    y = mean_treatment - mean_control 
    parts = state_key.split('-')
    #x = [1]
    x=[int(parts[5])]
    #occurs = min( dists_sed[root][2],dists_act[other][2])
    #y = mean_treatment
    
   
    return x,y
#,occurs

In [44]:
def get_all_xs_all_ys():
    all_xs = []
    all_ys = []
    for sk in sb:
        x,y =  get_x_y_dow(sk)
        #for j in range(o):
        #if 'gid-2' in sk:
        all_xs.append(x)
        all_ys.append(y)

    return all_xs,all_ys

In [45]:
X,y = get_all_xs_all_ys()

In [46]:
reg = LinearRegression().fit(X, y)

In [50]:
y

[-0.6471421535874873,
 -0.6471421535874873,
 -0.18967976557024713,
 -0.18967976557024713,
 0.06510089545032116,
 0.55943561983708,
 0.05898855064710684,
 0.0357177814411731,
 0.7336373495631747,
 0.7336373495631747,
 0.1493913851725086,
 0.1493913851725086,
 0.5436117068368445,
 0.5436117068368445,
 0.13341044535226665,
 0.13341044535226665,
 0.5394173216250291,
 0.5394173216250291,
 -0.09432047683364342,
 -0.09432047683364342,
 1.447018825504709,
 1.447018825504709,
 -0.22552821106053944,
 -0.2742590236033857,
 -0.11966154882027791,
 -0.11966154882027791,
 0.03383935219949308,
 0.03383935219949308,
 -0.3194705115799348,
 -0.3194705115799348,
 0.25080084683470716,
 0.25080084683470716,
 0.27358872022408454,
 0.01958827948273889,
 0.04784432729558574,
 -0.10853159646722066,
 0.01861383043639009,
 0.7593078606822026,
 0.06483311246756074,
 0.24343396839415732,
 0.21092540862210107,
 1.3012156878495031,
 0.3677363273766616,
 -0.04082077730392353,
 0.6777801165461956,
 0.6084733516192267,


In [47]:
reg.coef_

array([0.03572201])

In [48]:
 reg.intercept_

0.1676689911712402

In [41]:
reg.coef_

array([ 0.        , -0.11665832,  0.11808621,  0.15601783, -0.18131626,
        0.01280371])

In [42]:
 reg.intercept_

0.1422514939816639

In [52]:
reg.coef_

array([ 0.        , -0.06405887,  0.09447067,  0.16481901, -0.20736237,
        0.01136896])

In [53]:
 reg.intercept_

0.1318755103596786

In [23]:
with open('../../Downloads/distributions/day_to_id.pkl','rb') as f:
    h = pickle.load(f)

In [77]:
np.array(y).std()

0.5901814934881792

In [24]:
h

{0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 1, 6: 1}

In [67]:
def get_all_xs_all_ys_dow():
    ymean =[]
    ymean_wk = []
    for sk in sb:
        x,y =  get_x_y_dow(sk)
        if 'dow-0' in sk:
            
            ymean.append(y)
        elif 'dow-1' in sk:
            ymean_wk.append(y)
        

    return [[0],[1]],[np.array(ymean).mean(),np.array(ymean_wk).mean()]

In [68]:
X,y = get_all_xs_all_ys_dow()

In [69]:
reg = LinearRegression().fit(X, y)
reg.coef_

array([0.03572201])

In [70]:
    treatment = 'aint-1-'+state_key
    control = 'aint-0-'+state_key
    
    tother = matches_act[treatment]
    mean_treatment = dists_act[tother][0]
    
    cother = matches_act[control]
    mean_control = dists_act[cother][0

[0.16766899117124023, 0.20339099940289906]

In [134]:
def get_all_xs_all_ys_dow_fancy():
    y_0_1 = []
    y_0_0 = []
    y_1_1 = []
    y_1_0 = []
    
    seen = set([])
    
    for k,v in matches_act.items():
        if 'dow-0' in k and 'aint-1' in k:
            if len(v.split('-'))==10:
                
                y_0_1.append( dists_act[v][0])
            seen.add(v)
        elif 'dow-0'in k and 'aint-0' in k:
            if len(v.split('-'))==10:
                y_0_0.append( dists_act[v][0])
            seen.add(v)
        elif 'dow-1' in k and 'aint-0' in k:
            if len(v.split('-'))==10:
                y_1_0.append( dists_act[v][0])
            seen.add(v)
            #print('found')
        elif 'dow-1' in k and 'aint-1' in k:
            #print('found')
            if len(v.split('-'))==10:
                y_1_1.append( dists_act[v][0])
            seen.add(v)
    return np.array(y_0_1),np.array(y_0_0),np.array(y_1_0),np.array(y_1_1)

In [135]:
looks = get_all_xs_all_ys_dow_fancy()

In [136]:
looks[0].mean()

4.010646512693568

In [137]:
looks[1].mean()

4.294580149234434

In [138]:
looks[3].mean()

3.8597302105200364

In [139]:
looks[2].mean()

3.718651969105231

In [114]:
matches_act

{'aint-1-gid-2-tod-2-dow-0-wea-1-pre-0-loc-1': 'aint-1-gid-2-tod-2-dow-0-wea-1-pre-0-loc-1',
 'aint-1-gid-2-tod-1-dow-0-wea-0-pre-1-loc-1': 'aint-1-gid-2-tod-1-dow-0-wea-0-pre-1-loc-1',
 'aint-0-gid-2-tod-0-dow-1-wea-1-pre-0-loc-1': 'aint-0-gid-2-tod-0-dow-1-wea-1-pre-0',
 'aint-0-gid-2-tod-1-dow-0-wea-0-pre-1-loc-0': 'aint-0-gid-2-tod-1-dow-0-wea-0-pre-1-loc-0',
 'aint-1-gid-2-tod-1-dow-1-wea-0-pre-0-loc-1': 'aint-1-gid-2-tod-1-dow-1-wea-0-pre-0',
 'aint-0-gid-1-tod-2-dow-1-wea-0-pre-0-loc-0': 'aint-0-tod-2-dow-1-wea-0-pre-0',
 'aint-1-gid-2-tod-2-dow-0-wea-0-pre-1-loc-0': 'aint-1-gid-2-dow-0-wea-0-pre-1',
 'aint-0-gid-2-tod-0-dow-0-wea-0-pre-1-loc-1': 'aint-0-gid-2-tod-0-dow-0-wea-0-pre-1-loc-1',
 'aint-0-gid-1-tod-2-dow-0-wea-0-pre-0-loc-0': 'aint-0-gid-1-tod-2-dow-0-wea-0-pre-0',
 'aint-0-gid-1-tod-1-dow-0-wea-0-pre-1-loc-1': 'aint-0-tod-1-dow-0-wea-0-pre-1',
 'aint-0-gid-1-tod-2-dow-1-wea-0-pre-1-loc-0': 'aint-0-dow-1-wea-0-pre-1',
 'aint-0-gid-1-tod-2-dow-1-wea-1-pre-0-loc-0': 'a