In [1]:
import numpy as np
import pickle
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import pandas as pd
import sys
sys.path
sys.path.append('../models')
sys.path.append('../simulation')
import numpy as np
import pickle
import random
import os
import math
import sim_functions_cleaner  as sf
import operator
import study

In [1527]:
#orig np.array([0.13747917218640332, -0.08988142,   0.11982505, -0.16109622, 0.10403158])
coeffs =  np.array([0.05, 0.1,   -0.15,.1, -0.3, 0.15])
#coeffs = np.array([0.13747917218640332, -0.08988142,   0.11982505, -0.16109622, 0.10403158])


In [1528]:
#all_ys = [np.dot(coeffs.T,s) for s in data]

In [1529]:
def reward_percent_correct_aciton(percent):
    pass

In [2]:
with open('../simulation/visited_states_200.pkl','rb') as f:
    experiment = pickle.load(f)

4.681273138386588
4.606745807027805


In [3]:
def get_all_states():
    all_states = []
    counts = {}
    for person,data in experiment.population.items():
        h = data.history
        for time,cd in h.items():
            
            if cd['avail'] and cd['decision_time']:
                states = [1,cd['tod'],cd['dow'],cd['pretreatment'],cd['location']]
                key = '-'.join(str(i) for i in states)
                if key not in counts: 
                    counts[key]=0
                counts[key]=counts[key]+1
    return counts

In [4]:
s = get_all_states()


In [6]:
def get_percent(coeffs,s,p):
    average_add = []
    for k,v in s.items():
        state = [int(i) for i in k.split('-')]
        add = np.dot(coeffs.T,state)
        #print(add)
        temp = [add if add>0 else 0 for i in range(int(v*p)) ]
        temp_loss = [add if add<0 else 0 for i in range(int(v*(1-p))) ]
        #print(len(temp))
        #print(add)
        #print(int(v*(1-p)))
        #print(len(temp_loss))
        
        if p>0:
            
            average_add.extend(temp)
        if p<1:
            average_add.extend(temp_loss)
    return np.array(average_add).mean()


In [7]:
def get_adds(coeffs,s):
    average_add = []
    for k,v in s.items():
        state = [int(i) for i in k.split('-')]
        add = np.dot(coeffs.T,state)
        
            
        average_add.extend([add for i in range(v)])
     
    adds =  np.array(average_add)
    return len([ a for a in adds if a>0])/len(adds)

In [1535]:
adds = get_adds()

In [1536]:
perfect = get_percent(1)


In [1537]:
terrible = get_percent(0)


In [1538]:
perfect-terrible


0.18160447761194026

In [1539]:
##get percent optimal action for each case

len([ a for a in adds if a>0])/len(adds)


0.6263059701492537

In [1540]:
get_percent(.75)-get_percent(.6)


0.027422371866816314

In [1511]:
get_percent(.60)

0.15440516273849603

In [1526]:
s

{'1-0-0-1-0-0': 328,
 '1-0-0-1-1-0': 353,
 '1-1-0-1-1-0': 650,
 '1-1-0-1-0-0': 533,
 '1-0-0-1-0-1': 556,
 '1-1-0-1-1-1': 467,
 '1-1-0-1-0-1': 654,
 '1-0-0-1-1-1': 309,
 '1-0-1-1-1-1': 143,
 '1-0-1-1-0-1': 161,
 '1-1-1-1-0-1': 286,
 '1-1-1-1-1-0': 195,
 '1-0-1-1-0-0': 153,
 '1-0-1-1-1-0': 139,
 '1-1-1-1-0-0': 219,
 '1-1-1-1-1-1': 214}

In [1543]:
with open('../../Downloads/distributions/dists_anti_sedentary_4_4.pkl','rb') as f:
    dists_sed = pickle.load(f)
with open('../../Downloads/distributions/key_matches_anti_sedentary_4_4.pkl','rb') as f:
    matches_sed = pickle.load(f)
with open('../../Downloads/distributions/dists_activity_suggestion_4_4.pkl','rb') as f:
    dists_act = pickle.load(f)
with open('../../Downloads/distributions/key_matches_activity_suggestion_4_4.pkl','rb') as f:
    matches_act = pickle.load(f)
with open('../../Downloads/distributions/dists_base_4_4.pkl','rb') as f:
    dists_base = pickle.load(f)
with open('../../Downloads/distributions/key_matches_base_4_4.pkl','rb') as f:
    matches_base = pickle.load(f)

In [1546]:
np.arange(-.3,.3,.05)

array([-3.00000000e-01, -2.50000000e-01, -2.00000000e-01, -1.50000000e-01,
       -1.00000000e-01, -5.00000000e-02, -5.55111512e-17,  5.00000000e-02,
        1.00000000e-01,  1.50000000e-01,  2.00000000e-01,  2.50000000e-01])

In [18]:
def get_dif(coeffs,states):
    return get_percent(coeffs,s,.75)-get_percent(coeffs,s,.6)


In [9]:
def find_max():
    coeffs = np.array([0.05, 0.1,   -0.15,.1, -0.3, 0.15])
    therange = np.arange(-.3,.3,.05)
    maxval = -1 
    found = None
    avg=None
    for tod_val in therange:
        for dow_val in therange:
            for weather_val in therange:
                for preval in therange:
                    for locval in therange:
                        coeffs = np.array([0.05,tod_val,dow_val,preval,locval])
                        dif = get_dif(coeffs,s)
                        avg_send = get_adds(coeffs,s)
                        if dif>maxval and avg_send<.8 and avg_send>.4:
                            maxval=dif
                            found = coeffs
                            avg = avg_send
    return maxval,found,avg


In [10]:
find_max()


(0.04959121855103149,
 array([ 0.05,  0.25,  0.25,  0.25, -0.3 ]),
 0.748029991179065)

In [1577]:
find_max()


(0.042536475869809215,
 array([ 0.05,  0.2 , -0.2 ,  0.2 ,  0.2 , -0.3 ]),
 0.7861940298507463)

In [20]:
o=np.array([ 0.05,  0.25, .25 ,    0.25, -0.3])
print(get_dif(o,s))
print(get_adds(o,s))

0.04959121855103152
0.748029991179065


In [1599]:
o=np.array([  0.05,  0.25, -0.25,   0.25, -0.3 ])
print(get_dif(o,s))
print(get_adds(o,s))

0.037176051953289435
0.6455223880597015


In [1603]:
##no weather
find_max()

(0.05194505088007151,
 array([ 0.05,  0.25,  0.25,  0.25, -0.3 ]),
 0.7966417910447762)

In [ ]:
def get_x_y(state_key):
    root = matches_sed[ state_key]
    mean_control = dists_sed[root][0]
    other = matches_act[state_key]
    mean_treatment = dists_act[other][0]
    y = mean_treatment - mean_control 
    parts = state_key.split('-')
    x = [1]
    occurs = min( dists_sed[root][2],dists_act[other][2])

    if True:
    #len(root.split('-'))==14 and len(other.split('-'))==14:
        #print(root)
        #print(other)
        print(state_key)
        for i in range(5,len(parts),2):

                x.append(int(parts[i]))
        print(x)
    return x,y,dists_sed[root][1],dists_act[other][1],occurs,root,other
    