In [1]:
import numpy as np
import pickle
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import pandas as pd
import sys
sys.path
sys.path.append('../models')
sys.path.append('../simulation')
import numpy as np
import pickle
import random
import os
import math
import sim_functions_cleaner  as sf
import operator
import study

In [2]:
#orig np.array([0.13747917218640332, -0.08988142,   0.11982505, -0.16109622, 0.10403158])
coeffs =  np.array([0.05, 0.1,   -0.15,.1, -0.3, 0.15])
#coeffs = np.array([0.13747917218640332, -0.08988142,   0.11982505, -0.16109622, 0.10403158])


In [1528]:
#all_ys = [np.dot(coeffs.T,s) for s in data]

In [64]:
coeffs = np.array([-0.15285252,  0.29187095,  0.36084955,  0.19946275, -0.37852244])

In [1529]:
def reward_percent_correct_aciton(percent):
    pass

In [3]:
with open('../simulation/history_for_effect_case_three.pkl','rb') as f:
    experiment = pickle.load(f)
    

In [4]:
all_steps  = []
all_act = []
all_no_act = []
for p in experiment.population.values():
    # if  v['decision_time'] and v['avail'] 
    all_steps.extend([v['steps'] for k,v in p.history.items() if v['tod']!=2 ])
    all_act.extend([v['steps'] for k,v in p.history.items() if v['tod']!=2 \
                    and v['decision_time'] and v['avail'] and v['action']==1])
    all_no_act.extend([v['steps'] for k,v in p.history.items() if v['tod']!=2 \
                    and v['decision_time'] and v['avail'] and v['action']==0])

In [5]:
print(np.array(all_act).mean())
print(np.array(all_no_act).mean())

print(np.array(all_steps).mean())



4.897940506303782
4.597553604035779
4.961974944638608


In [20]:
def get_all_states():
    all_states = []
    counts = {}
    for person,data in experiment.population.items():
        h = data.history
        for time,cd in h.items():
            
            if cd['avail'] and cd['decision_time']:
                #cd['tod'],cd['dow'],
                states = [1,cd['dow'],cd['pretreatment'],cd['location']]
                key = '-'.join(str(i) for i in states)
                if key not in counts: 
                    counts[key]=0
                counts[key]=counts[key]+1
    return counts

In [21]:
s = get_all_states()


In [8]:
def get_percent(coeffs,s,p):
    average_add = []
    for k,v in s.items():
        state = [int(i) for i in k.split('-')]
        add = np.dot(coeffs.T,state)
        #print(add)
        temp = [add if add>0 else 0 for i in range(int(v*p)) ]
        temp_loss = [add if add<0 else 0 for i in range(int(v*(1-p))) ]
        #print(len(temp))
        #print(add)
        #print(int(v*(1-p)))
        #print(len(temp_loss))
        
        if p>0:
            
            average_add.extend(temp)
        if p<1:
            average_add.extend(temp_loss)
    return np.array(average_add).mean()


In [9]:
def get_adds(coeffs,s):
    average_add = []
    for k,v in s.items():
        state = [int(i) for i in k.split('-')]
        add = np.dot(coeffs.T,state)
        
            
        average_add.extend([add for i in range(v)])
     
    adds =  np.array(average_add)
    return len([ a for a in adds if a>0])/len(adds)


In [10]:
adds = get_adds(coeffs,s)


ValueError: shapes (6,) and (3,) not aligned: 6 (dim 0) != 3 (dim 0)

In [1536]:
perfect = get_percent(1)


In [1537]:
terrible = get_percent(0)


In [1538]:
perfect-terrible


0.18160447761194026

In [68]:
##get percent optimal action for each case

adds


0.5757128356556243

In [1540]:
get_percent(.75)-get_percent(.6)


0.027422371866816314

In [1511]:
get_percent(.60)

0.15440516273849603

In [1526]:
s

{'1-0-0-1-0-0': 328,
 '1-0-0-1-1-0': 353,
 '1-1-0-1-1-0': 650,
 '1-1-0-1-0-0': 533,
 '1-0-0-1-0-1': 556,
 '1-1-0-1-1-1': 467,
 '1-1-0-1-0-1': 654,
 '1-0-0-1-1-1': 309,
 '1-0-1-1-1-1': 143,
 '1-0-1-1-0-1': 161,
 '1-1-1-1-0-1': 286,
 '1-1-1-1-1-0': 195,
 '1-0-1-1-0-0': 153,
 '1-0-1-1-1-0': 139,
 '1-1-1-1-0-0': 219,
 '1-1-1-1-1-1': 214}

In [1543]:
with open('../../Downloads/distributions/dists_anti_sedentary_4_4.pkl','rb') as f:
    dists_sed = pickle.load(f)
with open('../../Downloads/distributions/key_matches_anti_sedentary_4_4.pkl','rb') as f:
    matches_sed = pickle.load(f)
with open('../../Downloads/distributions/dists_activity_suggestion_4_4.pkl','rb') as f:
    dists_act = pickle.load(f)
with open('../../Downloads/distributions/key_matches_activity_suggestion_4_4.pkl','rb') as f:
    matches_act = pickle.load(f)
with open('../../Downloads/distributions/dists_base_4_4.pkl','rb') as f:
    dists_base = pickle.load(f)
with open('../../Downloads/distributions/key_matches_base_4_4.pkl','rb') as f:
    matches_base = pickle.load(f)

In [1544]:
def get_all_states():
    gids = [1,2]
    tod = [0,1]
    dow  = [0,1]
    pretreatment = [0,1]
    temp = [0,1]
    loc = [0,1]
    
    all_states = []
    st = ['gid','tod','dow','wea','pre','loc']
    
    for g in gids:
        for t in tod:
            for d in dow:
                for tp in temp:
                    for p in pretreatment:
                        for l in loc:
                            all_states.append([g,t,d,tp,p,l])
    all_keys = []
    for s in all_states:
        new_key = ['aint','1']
        for i in range(len(s)):
            new_key.append(st[i])
            new_key.append(str(s[i]))
        all_keys.append('-'.join(new_key))
    return all_keys

In [1546]:
np.arange(-.3,.3,.05)

array([-3.00000000e-01, -2.50000000e-01, -2.00000000e-01, -1.50000000e-01,
       -1.00000000e-01, -5.00000000e-02, -5.55111512e-17,  5.00000000e-02,
        1.00000000e-01,  1.50000000e-01,  2.00000000e-01,  2.50000000e-01])

In [13]:
def get_dif(coeffs,states):
    return get_percent(coeffs,s,.8)-get_percent(coeffs,s,.6)


In [23]:
def find_max():
    #0.1,   -0.15,.1,
    coeffs = np.array([0.05, -0.15, -0.3, 0.15])
    therange = np.arange(-.35,.35,.05)
    maxval = -1 
    found = None
    avg=None
    #for tod_val in therange:
    for dow_val in therange:
        for weather_val in therange:
                for preval in therange:
                    for locval in therange:
                        #tod_val,dow_val,weather_val,
                        coeffs = np.array([0.05,dow_val,preval,locval])
                        dif = get_dif(coeffs,s)
                        avg_send = get_adds(coeffs,s)
                        if dif>maxval and avg_send<.8 and avg_send>.4:
                            maxval=dif
                            found = coeffs
                            avg = avg_send
    return maxval,found,avg


In [24]:
find_max()


(0.06269870786584403, array([ 0.05, -0.35,  0.3 ,  0.3 ]), 0.7688474670111655)

In [1577]:
find_max()


(0.042536475869809215,
 array([ 0.05,  0.2 , -0.2 ,  0.2 ,  0.2 , -0.3 ]),
 0.7861940298507463)

In [49]:
o=np.array([ 0.05,  0.2 ,  0.05,  0.25,  0.25, -0.3 ])
print(get_dif(o,s))
print(get_adds(o,s))


0.08360848344997726
0.8983681270214643


In [1599]:
o=np.array([  0.05,  0.25, -0.25,   0.25, -0.3 ])
print(get_dif(o,s))
print(get_adds(o,s))

0.037176051953289435
0.6455223880597015


In [1603]:
##no weather
find_max()

(0.05194505088007151,
 array([ 0.05,  0.25,  0.25,  0.25, -0.3 ]),
 0.7966417910447762)

In [ ]:
def get_x_y(state_key):
    root = matches_sed[ state_key]
    mean_control = dists_sed[root][0]
    other = matches_act[state_key]
    mean_treatment = dists_act[other][0]
    y = mean_treatment - mean_control 
    parts = state_key.split('-')
    x = [1]
    occurs = min( dists_sed[root][2],dists_act[other][2])

    if True:
    #len(root.split('-'))==14 and len(other.split('-'))==14:
        #print(root)
        #print(other)
        print(state_key)
        for i in range(5,len(parts),2):

                x.append(int(parts[i]))
        print(x)
    return x,y,dists_sed[root][1],dists_act[other][1],occurs,root,other
    