In [6]:
import pickle
import pandas as pd
import pytz

In [ ]:
Timestamp('2015-07-27 00:00:00-0500', tz='EST', freq='30T')

In [2]:
with open('../../Downloads/population_time_indices/all_ordered_times_Mondays.pkl','rb') as f:
    t = pickle.load(f)

In [4]:

with open('../../Downloads/population_time_indices/time_to_active_participants_pop_50.pkl','rb') as f:
    tt = pickle.load(f)

In [7]:
news = [ts.tz_localize(None) for ts in t]
    

In [10]:
with open('../../Downloads/population_time_indices/all_ordered_times_Mondays.pkl','wb') as f:
    pickle.dump(news,f)

In [ ]:
'aint-1-gid-1-tod-0-dow-0-wea-0-pre-1-loc-0'

In [11]:
with open('../../Downloads/current_distributions/key_matches_interventions.pkl','rb') as f:
    k = pickle.load(f)

In [14]:
'aint-1-gid-2-tod-0-dow-0-wea-1-pre-0-loc-0' in k

True

In [15]:
with open('../../Downloads/state_keys_one_hot.pkl','rb') as f:
    sk = pickle.load(f)

In [19]:
import numpy as np
z = np.zeros(12)

In [20]:
z[1:]=np.ones(11)

In [21]:
z

array([0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
z[-(4+1):]

array([1., 1., 1., 1., 1.])

In [25]:
.5*np.eye(2)

array([[0.5, 0. ],
       [0. , 0.5]])