In [5]:
import numpy as np
import random
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from scipy.interpolate import BSpline

In [2]:
x_vec = [[random.random()] for i in range(1000)]

In [17]:
poly = PolynomialFeatures(degree=3, include_bias=True)

In [19]:
X_poly = poly.fit_transform(x_vec)

In [22]:
model = LinearRegression(fit_intercept=False)

In [23]:
y = [x[0] for x in x_vec]

In [24]:
model.fit(X_poly,y )

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=1, normalize=False)

In [26]:
model.coef_.shape

(5,)

In [6]:
knots = np.arange(0,10,10/50)

In [7]:
knots

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8])

In [54]:
b = BSpline(knots,c,3)

In [55]:
c = [1]
c.extend([0 for i in range(49)])

In [56]:
b(y)

array([  2.41128257e+00,   6.46279988e+00,   0.00000000e+00,
         3.48111598e+00,   1.43085491e-04,   1.09267787e+00,
         6.50752206e+00,   4.20943086e+00,   3.26133949e+00,
         1.04875249e+01,   2.02632431e+00,   1.30820694e+00,
         3.80024977e+00,   1.65249514e-02,   1.10506543e+00,
         1.91959733e-01,   4.95332278e+00,   2.41079870e-02,
         6.00812399e+00,   4.18352878e+00,   8.40374069e+00,
         7.61834298e+00,   2.32510022e+00,   4.17584243e+00,
         5.49153562e+00,   6.70103083e+00,   0.00000000e+00,
         1.82470021e+00,   2.21718566e+00,   9.61629472e-02,
         0.00000000e+00,   1.05123220e+01,   0.00000000e+00,
         2.63620715e+00,   2.81133212e+00,   1.51660384e-01,
         0.00000000e+00,   2.47549617e+00,   1.00069842e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         4.06650633e-01,   4.50883096e+00,   6.03203653e-01,
         0.00000000e+00,   4.32679418e-01,   4.26993749e-02,
         5.42598180e-04,

In [51]:
len(knots)

50

In [14]:
c = np.zeros(49)

In [15]:
c.put(0,1)

In [1]:
from geomdl import BSpline

In [2]:
curve = BSpline.Curve()

In [19]:
curve.degree = 4
curve.ctrlpts = [[k] for k in knots]
curve.bbox = [0,10]

AttributeError: can't set attribute

In [17]:
c

array([ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [34]:
from scipy.interpolate import BSpline


knots = np.arange(0,10,(10-0)/50)
            
c = np.zeros(50)
c.put(0,1)
b = BSpline(knots,c,4,extrapolate='periodic')

In [24]:
X = np.arange(0,1/(1-.9),.01)

In [36]:
knots

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8])

In [35]:
b(X)

array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

In [37]:
X

array([  0.  ,   0.01,   0.02, ...,   9.98,   9.99,  10.  ])