In [1]:
import bandit
from numpy.random import uniform
from numpy.linalg import solve
import numpy as np
import state_params
import random
from scipy.stats import norm
import TS_fancy
from scipy.linalg import block_diag
from scipy.interpolate import BSpline
import eta

In [2]:
sp = state_params.state_params(10)

In [3]:
def simulate(pZ,init):
    total_reward = 0
  # simulation
    nT = 450

      # initial state
    Z_init = [uniform() for i in range(pZ)]
    X_init =0
    I_init = (uniform() < 0.8)
  

  
    # policy initilization
    mu_beta = init.mu_2
    Sigma_beta = init.sigma_2
    
    
    eta_function = eta.eta()
    
    # placeholder
    batch = [[] for i in range(nT)]
  
  
    # performance matrix

  
  
    for t in range(nT):
    
    
    # current state 
    
        if(t==0):
      
            Z_next = Z_init
            X_next = X_init
            I_next = I_init
      
    
    
        Z = Z_next
        X = X_next
        I = I_next
    
    # action selection
    
        if I == 1:
      
          # calculate prob
      
            prob = TS_fancy.prob_cal(Z, X, mu_beta, Sigma_beta, init, eta_function.eta_init)
            #print(prob)
            #print(':)')
          # sample the action
            A = int(uniform() < prob)
      
        else:
      
            prob = 0
            A = 0
      
        
    
        R = 1+Z[0]+(Z[0]**2)-(.05*X)+A*(1-.1*X)+np.random.normal(scale=1)
        Z_next = [uniform() for i in range(pZ)]
        X_next = TS_fancy.gen_nextdosage(X,A)
        I_next = (uniform()<.8)
        
        
        batch[t]=TS_fancy.make_batch(t,Z,X,I,A,prob,R)
        
        
        total_reward = total_reward+R
        if (t+1)%5 == 0: 
            if (t+1)%35==0:  
            #update the txt effect posterior
                temp = TS_fancy.policy_update(batch[:t], init,proxy=True)
                print('returning temp')
                return temp
            #print(temp)
                mu_beta = temp[0]
                Sigma_beta = temp[1]
                #eta_function = temp[2]
            else:
                temp = TS_fancy.policy_update(batch[:t], init,proxy=False)
               
            #print(temp)
                mu_beta = temp[0]
                Sigma_beta = temp[1]
      
   
    
        #policy_update_ts(batch, init)
    print(total_reward)
    return batch,total_reward
  
    


In [11]:
b,t =simulate(sp.pZ,sp)

called F all


In [4]:
play =simulate(sp.pZ,sp)

0.012968778610229492
returning temp


In [5]:
np.array(play).shape

(1001,)

In [6]:
play

[array([ 26.04166667,  25.01552109,  24.02000417, ...,   0.        ,
          0.        ,   0.        ]),
 array([-76.20833333, -72.85523021, -69.61101667, ...,   0.        ,
          0.        ,   0.        ]),
 array([ 90.45833333,  86.2571474 ,  82.20135833, ...,   0.        ,
          0.        ,   0.        ]),
 array([-49.95833333, -47.56068854, -45.24968333, ...,   0.        ,
          0.        ,   0.        ]),
 array([ 10.66666667,  10.14325026,   9.6393375 , ...,   0.        ,
          0.        ,   0.        ]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0

In [17]:
#range=c(0, 1/(1-input$lambda)), nbasis=50, norder = 4)
BSpline(np.arange(0,1/0.1+1),50,4)

AttributeError: 'int' object has no attribute 'ndim'

In [6]:
np.arange(0,10,(10)/50)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8])

In [6]:
np.arange(0,1/(1-.9),.01)

array([  0.  ,   0.01,   0.02, ...,   9.98,   9.99,  10.  ])